version: '2'

services:
  web:
    image: srlapi
    container_name: srl_api
    hostname: api
    command: npm run dev # npm start for production
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      COOKIE_DOMAIN:
    volumes:
      - "./src:/app/src"
    ports:
      - '3000:3000'
    networks:
      api:
  mysql:
    image: 'mariadb:10.1'
    container_name: mysql_api
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: srl_data
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      api:
  redis:
    image: 'redis:3.2.6-alpine'
    container_name: redis_api
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      api:

networks:
  api:
    driver: bridge
